### ISSUE TITLE
E_INVALID_PARAMETER: twitch is not a valid ally driver

### ISSUE THREAD

**Issue by BrunoLagoa** [mikield/adonis-ally-extended#1]
Hello, I'm trying to use your extension, but when I have any of the 3 drivers I have this error. can you help me? I'm using the adonisjs version: 4.1

https://prnt.sc/nemxfg

**Comment by tribefireapp** [comment]
> Hello, I'm trying to use your extension, but when I have any of the 3 drivers I have this error. can you help me? I'm using the adonisjs version: 4.1
> 
> https://prnt.sc/nemxfg

Did you end up fixing this?

**Comment by mikield** [comment]
@BrunoLagoa have not tested that in 4.1 version.

Maybe there was a major update that has broken registration of providers for ally.
Will look at that, and push an update if needed.

**Comment by mikield** [comment]
Also please provide some code.

**Comment by mikield** [comment]
@BrunoLagoa this issue was fixed. Please upgrade to  version`0.7.2`.

Also take a look that now you don't need to call anything into `start/hooks.js`.
All drivers will be registered, and will be created once you call them.
